export const SupportLangaues = [
    { "code": "en", "name": "English" },
    { "code": "zh-Hans", "name": "Chinese (Simplified)" },
    { "code": "es", "name": "Spanish" },
    { "code": "fr", "name": "French" },
    { "code": "de", "name": "German" },
    { "code": "ja", "name": "Japanese" },
    { "code": "pt", "name": "Portuguese" },
    { "code": "ru", "name": "Russian" },
    { "code": "ar", "name": "Arabic" },
    { "code": "ko", "name": "Korean" },
    { "code": "it", "name": "Italian" },
    { "code": "tr", "name": "Turkish" },
    { "code": "vi", "name": "Vietnamese" },
    { "code": "pl", "name": "Polish" },
    { "code": "nl", "name": "Dutch" },
    { "code": "sv", "name": "Swedish" },
    { "code": "da", "name": "Danish" },
    { "code": "no", "name": "Norwegian" },
    { "code": "fi", "name": "Finnish" },
    { "code": "el", "name": "Greek" },
    { "code": "he", "name": "Hebrew" },
    { "code": "hi", "name": "Hindi" },
    { "code": "th", "name": "Thai" },
    { "code": "cs", "name": "Czech" },
    { "code": "hu", "name": "Hungarian" },
    { "code": "ro", "name": "Romanian" },
    { "code": "sk", "name": "Slovak" },
    { "code": "bg", "name": "Bulgarian" }
  ]
  